# AI Agents Configuration
version: '1.0'

# Global Agent Settings
global_settings:
  default_model: 'llama-3.1-nemotron-ultra-253b'
  timeout: 30
  max_retries: 3
  cache_duration: 3600
  logging_level: 'INFO'
  rate_limit: 100

# AI Models Configuration
models:
  llama-3.1-nemotron-ultra:
    api_version: '1.0'
    temperature: 0.7
    max_tokens: 4096
    top_p: 0.95
    presence_penalty: 0.1
    frequency_penalty: 0.1
    stop_sequences: ["\n\n", "###"]
    model_params:
      context_window: 32768
      embedding_size: 253000000000
      architecture: "LLaMA-3.1"
      provider: "NVIDIA"

# Agent Configurations
agents:
  sdg_analyzer:
    name: "SDG & ESG Analyzer"
    description: "Analyzes company alignment with SDGs and ESG principles"
    model: "llama-3.1-nemotron-ultra"
    priority: 1
    capabilities:
      - esg_analysis
      - sdg_alignment
      - impact_assessment
      - risk_evaluation
    parameters:
      analysis_depth: "comprehensive"
      data_freshness: 86400
      confidence_threshold: 0.8
    rate_limit: 50
    cache_enabled: true

  sentiment_analyzer:
    name: "Market Sentiment Analyzer"
    description: "Analyzes market sentiment and public perception"
    model: "llama-3.1-nemotron-ultra"
    priority: 2
    capabilities:
      - sentiment_analysis
      - news_processing
      - social_media_analysis
      - controversy_detection
    parameters:
      sentiment_threshold: 0.6
      time_window: 604800
      source_weight:
        news: 0.4
        social_media: 0.3
        analyst_reports: 0.3
    rate_limit: 100
    cache_enabled: true

  financial_analyzer:
    name: "Financial Health Analyzer"
    description: "Analyzes financial metrics and market performance"
    model: "llama-3.1-nemotron-ultra"
    priority: 1
    capabilities:
      - financial_analysis
      - market_analysis
      - risk_assessment
      - peer_comparison
    parameters:
      analysis_period: 90
      metrics_threshold: 0.7
      update_frequency: 3600
    rate_limit: 75
    cache_enabled: true

  investment_advisor:
    name: "Investment Recommendation Engine"
    description: "Generates final investment recommendations"
    model: "llama-3.1-nemotron-ultra"
    priority: 1
    capabilities:
      - recommendation_generation
      - risk_profiling
      - portfolio_optimization
      - strategy_development
    parameters:
      confidence_threshold: 0.85
      risk_tolerance: "moderate"
      time_horizon: "long_term"
    rate_limit: 50
    cache_enabled: true

# Error Handling
error_handling:
  retry_attempts: 3
  backoff_factor: 2
  timeout: 30
  fallback_strategy: "cache"
  alert_threshold: 5

# Monitoring
monitoring:
  performance_metrics: true
  error_tracking: true
  usage_analytics: true
  health_checks: true
  alert_channels:
    - email
    - slack
    - dashboard

# Security
security:
  api_key_rotation: 30
  request_encryption: true
  response_encryption: true
  data_retention: 90
  access_control:
    rate_limiting: true
    ip_whitelist: true
    auth_required: true

sdg_ethical_analyst:
  role: SDG and Ethical Analysis Expert
  goal: Analyze companies for SDG alignment and ethical practices, providing comprehensive ethical scores
  backstory: >
    You are an expert in sustainable development and ethical business practices with deep knowledge of UN SDGs
    and ESG metrics. Your analysis helps ensure investments align with sustainable and ethical principles.
    You have extensive experience in evaluating corporate sustainability reports and ethical business practices.

sentiment_analyst:
  role: Market Sentiment Analysis Expert
  goal: Analyze market sentiment and public perception of companies to generate accurate sentiment scores
  backstory: >
    You are a seasoned market analyst specializing in sentiment analysis across various data sources.
    Your expertise includes analyzing news, social media, and market trends to gauge public perception
    and market sentiment accurately.

financial_analyst:
  role: Financial Analysis Expert
  goal: Conduct thorough financial analysis of companies to assess their financial health and market position
  backstory: >
    You are a veteran financial analyst with extensive experience in evaluating company financials,
    market performance, and investment potential. Your analysis combines traditional metrics with
    modern market indicators to provide comprehensive financial assessments.

investment_advisor:
  role: Responsible Investment Advisor
  goal: Synthesize all analyses to provide balanced, responsible investment recommendations
  backstory: >
    You are a distinguished investment advisor specializing in responsible investing. Your expertise
    lies in balancing ethical considerations with financial returns. You have a proven track record
    of helping clients make investment decisions that are both profitable and socially responsible. 